apiVersion: v1
kind: Service
metadata:
  name: flask-deployment
  labels:
    app: flask-deployment
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask-deployment
