apiVersion: v1
kind: Service
metadata:
  name: flask-deployment-node-port
spec:
  type: NodePort
  selector:
    app: flask-deployment
  ports:
    - port: 5000
      targetPort: 5000
      nodePort:  30007
